/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `activity`;

CREATE TABLE `activity` (
  `activity_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `activity_unique` TEXT NOT NULL,
  `activity_name` TEXT NOT NULL,
  `activity_price` INT NOT NULL,
  `activity_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

