/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `address`;

CREATE TABLE `address` (
  `address_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `address_unique` TEXT NOT NULL,
  `address_name` TEXT NOT NULL,
  `address_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

