// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ADDRESS_ODB_HXX
#define ADDRESS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "address.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // address
  //
  template <>
  struct class_traits< ::address >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::address >
  {
    public:
    typedef ::address object_type;
    typedef ::address* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // address
  //
  template <typename A>
  struct query_columns< ::address, id_mysql, A >
  {
    // address_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    address_id_type_;

    static const address_id_type_ address_id;

    // address_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    address_unique_type_;

    static const address_unique_type_ address_unique;

    // address_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    address_name_type_;

    static const address_name_type_ address_name;

    // address_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    address_reg_date_type_;

    static const address_reg_date_type_ address_reg_date;
  };

  template <typename A>
  const typename query_columns< ::address, id_mysql, A >::address_id_type_
  query_columns< ::address, id_mysql, A >::
  address_id (A::table_name, "`address_id`", 0);

  template <typename A>
  const typename query_columns< ::address, id_mysql, A >::address_unique_type_
  query_columns< ::address, id_mysql, A >::
  address_unique (A::table_name, "`address_unique`", 0);

  template <typename A>
  const typename query_columns< ::address, id_mysql, A >::address_name_type_
  query_columns< ::address, id_mysql, A >::
  address_name (A::table_name, "`address_name`", 0);

  template <typename A>
  const typename query_columns< ::address, id_mysql, A >::address_reg_date_type_
  query_columns< ::address, id_mysql, A >::
  address_reg_date (A::table_name, "`address_reg_date`", 0);

  template <typename A>
  struct pointer_query_columns< ::address, id_mysql, A >:
    query_columns< ::address, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::address, id_mysql >:
    public access::object_traits< ::address >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // address_id
      //
      unsigned long long address_id_value;
      my_bool address_id_null;

      // address_unique
      //
      details::buffer address_unique_value;
      unsigned long address_unique_size;
      my_bool address_unique_null;

      // address_name
      //
      details::buffer address_name_value;
      unsigned long address_name_size;
      my_bool address_name_null;

      // address_reg_date
      //
      details::buffer address_reg_date_value;
      unsigned long address_reg_date_size;
      my_bool address_reg_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::address, id_common >:
    public access::object_traits_impl< ::address, id_mysql >
  {
  };

  // address
  //
}

#include "address-odb.ixx"

#include <odb/post.hxx>

#endif // ADDRESS_ODB_HXX
