// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef BILL_ODB_HXX
#define BILL_ODB_HXX

// Begin prologue.
//
#include <odb/boost/smart-ptr/pointer-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "bill.hxx"

#include "branch-odb.hxx"
#include "customer-odb.hxx"
#include "meter-odb.hxx"
#include "unit-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // bill
  //
  template <>
  struct class_traits< ::bill >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::bill >
  {
    public:
    typedef ::bill object_type;
    typedef ::boost::shared_ptr< ::bill > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // bill
  //
  template <typename A>
  struct pointer_query_columns< ::bill, id_mysql, A >
  {
    // bill_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_id_type_;

    static const bill_id_type_ bill_id;

    // bill_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_unique_type_;

    static const bill_unique_type_ bill_unique;

    // bill_customer
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_customer_type_;

    static const bill_customer_type_ bill_customer;

    // bill_meter
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_meter_type_;

    static const bill_meter_type_ bill_meter;

    // bill_unit
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_unit_type_;

    static const bill_unit_type_ bill_unit;

    // bill_unit_used
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_unit_used_type_;

    static const bill_unit_used_type_ bill_unit_used;

    // bill_cost
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_cost_type_;

    static const bill_cost_type_ bill_cost;

    // bill_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_reg_date_type_;

    static const bill_reg_date_type_ bill_reg_date;
  };

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_id_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_id (A::table_name, "`bill_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_unique_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_unique (A::table_name, "`bill_unique`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_customer_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_customer (A::table_name, "`bill_customer`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_meter_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_meter (A::table_name, "`bill_meter`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_unit_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_unit (A::table_name, "`bill_unit`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_unit_used_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_unit_used (A::table_name, "`bill_unit_used`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_cost_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_cost (A::table_name, "`bill_cost`", 0);

  template <typename A>
  const typename pointer_query_columns< ::bill, id_mysql, A >::bill_reg_date_type_
  pointer_query_columns< ::bill, id_mysql, A >::
  bill_reg_date (A::table_name, "`bill_reg_date`", 0);

  template <>
  class access::object_traits_impl< ::bill, id_mysql >:
    public access::object_traits< ::bill >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // bill_id
      //
      unsigned long long bill_id_value;
      my_bool bill_id_null;

      // bill_unique
      //
      details::buffer bill_unique_value;
      unsigned long bill_unique_size;
      my_bool bill_unique_null;

      // bill_customer
      //
      unsigned long long bill_customer_value;
      my_bool bill_customer_null;

      // bill_meter
      //
      unsigned long long bill_meter_value;
      my_bool bill_meter_null;

      // bill_unit
      //
      unsigned long long bill_unit_value;
      my_bool bill_unit_null;

      // bill_unit_used
      //
      details::buffer bill_unit_used_value;
      unsigned long bill_unit_used_size;
      my_bool bill_unit_used_null;

      // bill_cost
      //
      details::buffer bill_cost_value;
      unsigned long bill_cost_size;
      my_bool bill_cost_null;

      // bill_reg_date
      //
      details::buffer bill_reg_date_value;
      unsigned long bill_reg_date_size;
      my_bool bill_reg_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct bill_customer_tag;
    struct bill_meter_tag;
    struct bill_unit_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::bill, id_common >:
    public access::object_traits_impl< ::bill, id_mysql >
  {
  };

  // bill
  //
  template <>
  struct alias_traits<
    ::customer,
    id_mysql,
    access::object_traits_impl< ::bill, id_mysql >::bill_customer_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::meter,
    id_mysql,
    access::object_traits_impl< ::bill, id_mysql >::bill_meter_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::unit,
    id_mysql,
    access::object_traits_impl< ::bill, id_mysql >::bill_unit_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::bill, id_mysql >
  {
    // bill_customer
    //
    typedef
    odb::alias_traits<
      ::customer,
      id_mysql,
      access::object_traits_impl< ::bill, id_mysql >::bill_customer_tag>
    bill_customer_alias_;

    // bill_meter
    //
    typedef
    odb::alias_traits<
      ::meter,
      id_mysql,
      access::object_traits_impl< ::bill, id_mysql >::bill_meter_tag>
    bill_meter_alias_;

    // bill_unit
    //
    typedef
    odb::alias_traits<
      ::unit,
      id_mysql,
      access::object_traits_impl< ::bill, id_mysql >::bill_unit_tag>
    bill_unit_alias_;
  };

  template <typename A>
  struct query_columns< ::bill, id_mysql, A >:
    query_columns_base< ::bill, id_mysql >
  {
    // bill_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_id_type_;

    static const bill_id_type_ bill_id;

    // bill_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_unique_type_;

    static const bill_unique_type_ bill_unique;

    // bill_customer
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_customer_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::customer,
        id_mysql,
        bill_customer_alias_ > >
    bill_customer_pointer_type_;

    struct bill_customer_type_: bill_customer_pointer_type_, bill_customer_column_type_
    {
      bill_customer_type_ (const char* t, const char* c, const char* conv)
        : bill_customer_column_type_ (t, c, conv)
      {
      }
    };

    static const bill_customer_type_ bill_customer;

    // bill_meter
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_meter_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::meter,
        id_mysql,
        bill_meter_alias_ > >
    bill_meter_pointer_type_;

    struct bill_meter_type_: bill_meter_pointer_type_, bill_meter_column_type_
    {
      bill_meter_type_ (const char* t, const char* c, const char* conv)
        : bill_meter_column_type_ (t, c, conv)
      {
      }
    };

    static const bill_meter_type_ bill_meter;

    // bill_unit
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    bill_unit_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::unit,
        id_mysql,
        bill_unit_alias_ > >
    bill_unit_pointer_type_;

    struct bill_unit_type_: bill_unit_pointer_type_, bill_unit_column_type_
    {
      bill_unit_type_ (const char* t, const char* c, const char* conv)
        : bill_unit_column_type_ (t, c, conv)
      {
      }
    };

    static const bill_unit_type_ bill_unit;

    // bill_unit_used
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_unit_used_type_;

    static const bill_unit_used_type_ bill_unit_used;

    // bill_cost
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_cost_type_;

    static const bill_cost_type_ bill_cost;

    // bill_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    bill_reg_date_type_;

    static const bill_reg_date_type_ bill_reg_date;
  };

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_id_type_
  query_columns< ::bill, id_mysql, A >::
  bill_id (A::table_name, "`bill_id`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_unique_type_
  query_columns< ::bill, id_mysql, A >::
  bill_unique (A::table_name, "`bill_unique`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_customer_type_
  query_columns< ::bill, id_mysql, A >::
  bill_customer (A::table_name, "`bill_customer`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_meter_type_
  query_columns< ::bill, id_mysql, A >::
  bill_meter (A::table_name, "`bill_meter`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_unit_type_
  query_columns< ::bill, id_mysql, A >::
  bill_unit (A::table_name, "`bill_unit`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_unit_used_type_
  query_columns< ::bill, id_mysql, A >::
  bill_unit_used (A::table_name, "`bill_unit_used`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_cost_type_
  query_columns< ::bill, id_mysql, A >::
  bill_cost (A::table_name, "`bill_cost`", 0);

  template <typename A>
  const typename query_columns< ::bill, id_mysql, A >::bill_reg_date_type_
  query_columns< ::bill, id_mysql, A >::
  bill_reg_date (A::table_name, "`bill_reg_date`", 0);
}

#include "bill-odb.ixx"

#include <odb/post.hxx>

#endif // BILL_ODB_HXX
