/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `bill`;

CREATE TABLE `bill` (
  `bill_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `bill_unique` TEXT NOT NULL,
  `bill_customer` BIGINT UNSIGNED NULL,
  `bill_meter` BIGINT UNSIGNED NULL,
  `bill_unit` BIGINT UNSIGNED NULL,
  `bill_unit_used` TEXT NOT NULL,
  `bill_cost` TEXT NOT NULL,
  `bill_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `bill`
  ADD CONSTRAINT `bill_bill_customer_fk`
    FOREIGN KEY (`bill_customer`)
    REFERENCES `customer` (`customer_id`),
  ADD CONSTRAINT `bill_bill_meter_fk`
    FOREIGN KEY (`bill_meter`)
    REFERENCES `meter` (`meter_id`),
  ADD CONSTRAINT `bill_bill_unit_fk`
    FOREIGN KEY (`bill_unit`)
    REFERENCES `unit` (`unit_id`)
*/

