/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `branch`;

CREATE TABLE `branch` (
  `branch_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `branch_unique` TEXT NOT NULL,
  `branch_name` TEXT NOT NULL,
  `branch_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

