/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `checkin`;

CREATE TABLE `checkin` (
  `checkin_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `checkin_unique` TEXT NOT NULL,
  `checkin_employee` INT NOT NULL,
  `checkin_in` TEXT NOT NULL,
  `checkin_out` TEXT NOT NULL,
  `checkin_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

