// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef COMPANIES_ODB_HXX
#define COMPANIES_ODB_HXX

// Begin prologue.
//
#include <odb/boost/smart-ptr/pointer-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "companies.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // companies
  //
  template <>
  struct class_traits< ::companies >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::companies >
  {
    public:
    typedef ::companies object_type;
    typedef ::boost::shared_ptr< ::companies > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // companies
  //
  template <typename A>
  struct query_columns< ::companies, id_mysql, A >
  {
    // company_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    company_id_type_;

    static const company_id_type_ company_id;

    // company
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    company_type_;

    static const company_type_ company;

    // database_username
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    database_username_type_;

    static const database_username_type_ database_username;

    // database_password
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    database_password_type_;

    static const database_password_type_ database_password;

    // database_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    database_name_type_;

    static const database_name_type_ database_name;
  };

  template <typename A>
  const typename query_columns< ::companies, id_mysql, A >::company_id_type_
  query_columns< ::companies, id_mysql, A >::
  company_id (A::table_name, "`company_id`", 0);

  template <typename A>
  const typename query_columns< ::companies, id_mysql, A >::company_type_
  query_columns< ::companies, id_mysql, A >::
  company (A::table_name, "`company`", 0);

  template <typename A>
  const typename query_columns< ::companies, id_mysql, A >::database_username_type_
  query_columns< ::companies, id_mysql, A >::
  database_username (A::table_name, "`database_username`", 0);

  template <typename A>
  const typename query_columns< ::companies, id_mysql, A >::database_password_type_
  query_columns< ::companies, id_mysql, A >::
  database_password (A::table_name, "`database_password`", 0);

  template <typename A>
  const typename query_columns< ::companies, id_mysql, A >::database_name_type_
  query_columns< ::companies, id_mysql, A >::
  database_name (A::table_name, "`database_name`", 0);

  template <typename A>
  struct pointer_query_columns< ::companies, id_mysql, A >:
    query_columns< ::companies, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::companies, id_mysql >:
    public access::object_traits< ::companies >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // company_id
      //
      unsigned long long company_id_value;
      my_bool company_id_null;

      // company
      //
      details::buffer company_value;
      unsigned long company_size;
      my_bool company_null;

      // database_username
      //
      details::buffer database_username_value;
      unsigned long database_username_size;
      my_bool database_username_null;

      // database_password
      //
      details::buffer database_password_value;
      unsigned long database_password_size;
      my_bool database_password_null;

      // database_name
      //
      details::buffer database_name_value;
      unsigned long database_name_size;
      my_bool database_name_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::companies, id_common >:
    public access::object_traits_impl< ::companies, id_mysql >
  {
  };

  // companies
  //
}

#include "companies-odb.ixx"

#include <odb/post.hxx>

#endif // COMPANIES_ODB_HXX
