/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `companies`;

CREATE TABLE `companies` (
  `company_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `company` TEXT NOT NULL,
  `database_username` TEXT NOT NULL,
  `database_password` TEXT NOT NULL,
  `database_name` TEXT NOT NULL)
 ENGINE=InnoDB;

