/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `customer`;

CREATE TABLE `customer` (
  `customer_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `customer_unique` TEXT NOT NULL,
  `customer_branch` BIGINT UNSIGNED NULL,
  `customer_name` TEXT NOT NULL,
  `customer_gender` TEXT NOT NULL,
  `customer_contact` TEXT NOT NULL,
  `customer_address` TEXT NOT NULL,
  `customer_house_number` TEXT NULL,
  `customer_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `customer`
  ADD CONSTRAINT `customer_customer_branch_fk`
    FOREIGN KEY (`customer_branch`)
    REFERENCES `branch` (`branch_id`)
*/

