// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef CUSTOMER_ODB_HXX
#define CUSTOMER_ODB_HXX

// Begin prologue.
//
#include <odb/boost/smart-ptr/pointer-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "customer.hxx"

#include "branch-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // customer
  //
  template <>
  struct class_traits< ::customer >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::customer >
  {
    public:
    typedef ::customer object_type;
    typedef ::boost::shared_ptr< ::customer > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // customer
  //
  template <typename A>
  struct pointer_query_columns< ::customer, id_mysql, A >
  {
    // customer_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    customer_id_type_;

    static const customer_id_type_ customer_id;

    // customer_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_unique_type_;

    static const customer_unique_type_ customer_unique;

    // customer_branch
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    customer_branch_type_;

    static const customer_branch_type_ customer_branch;

    // customer_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_name_type_;

    static const customer_name_type_ customer_name;

    // customer_gender
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_gender_type_;

    static const customer_gender_type_ customer_gender;

    // customer_contact
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_contact_type_;

    static const customer_contact_type_ customer_contact;

    // customer_address
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_address_type_;

    static const customer_address_type_ customer_address;

    // customer_house_number
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_house_number_type_;

    static const customer_house_number_type_ customer_house_number;

    // customer_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_reg_date_type_;

    static const customer_reg_date_type_ customer_reg_date;
  };

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_id_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_id (A::table_name, "`customer_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_unique_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_unique (A::table_name, "`customer_unique`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_branch_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_branch (A::table_name, "`customer_branch`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_name_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_name (A::table_name, "`customer_name`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_gender_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_gender (A::table_name, "`customer_gender`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_contact_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_contact (A::table_name, "`customer_contact`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_address_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_address (A::table_name, "`customer_address`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_house_number_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_house_number (A::table_name, "`customer_house_number`", 0);

  template <typename A>
  const typename pointer_query_columns< ::customer, id_mysql, A >::customer_reg_date_type_
  pointer_query_columns< ::customer, id_mysql, A >::
  customer_reg_date (A::table_name, "`customer_reg_date`", 0);

  template <>
  class access::object_traits_impl< ::customer, id_mysql >:
    public access::object_traits< ::customer >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // customer_id
      //
      unsigned long long customer_id_value;
      my_bool customer_id_null;

      // customer_unique
      //
      details::buffer customer_unique_value;
      unsigned long customer_unique_size;
      my_bool customer_unique_null;

      // customer_branch
      //
      unsigned long long customer_branch_value;
      my_bool customer_branch_null;

      // customer_name
      //
      details::buffer customer_name_value;
      unsigned long customer_name_size;
      my_bool customer_name_null;

      // customer_gender
      //
      details::buffer customer_gender_value;
      unsigned long customer_gender_size;
      my_bool customer_gender_null;

      // customer_contact
      //
      details::buffer customer_contact_value;
      unsigned long customer_contact_size;
      my_bool customer_contact_null;

      // customer_address
      //
      details::buffer customer_address_value;
      unsigned long customer_address_size;
      my_bool customer_address_null;

      // customer_house_number
      //
      details::buffer customer_house_number_value;
      unsigned long customer_house_number_size;
      my_bool customer_house_number_null;

      // customer_reg_date
      //
      details::buffer customer_reg_date_value;
      unsigned long customer_reg_date_size;
      my_bool customer_reg_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct customer_branch_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::customer, id_common >:
    public access::object_traits_impl< ::customer, id_mysql >
  {
  };

  // customer
  //
  template <>
  struct alias_traits<
    ::branch,
    id_mysql,
    access::object_traits_impl< ::customer, id_mysql >::customer_branch_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::customer, id_mysql >
  {
    // customer_branch
    //
    typedef
    odb::alias_traits<
      ::branch,
      id_mysql,
      access::object_traits_impl< ::customer, id_mysql >::customer_branch_tag>
    customer_branch_alias_;
  };

  template <typename A>
  struct query_columns< ::customer, id_mysql, A >:
    query_columns_base< ::customer, id_mysql >
  {
    // customer_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    customer_id_type_;

    static const customer_id_type_ customer_id;

    // customer_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_unique_type_;

    static const customer_unique_type_ customer_unique;

    // customer_branch
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    customer_branch_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::branch,
        id_mysql,
        customer_branch_alias_ > >
    customer_branch_pointer_type_;

    struct customer_branch_type_: customer_branch_pointer_type_, customer_branch_column_type_
    {
      customer_branch_type_ (const char* t, const char* c, const char* conv)
        : customer_branch_column_type_ (t, c, conv)
      {
      }
    };

    static const customer_branch_type_ customer_branch;

    // customer_name
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_name_type_;

    static const customer_name_type_ customer_name;

    // customer_gender
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_gender_type_;

    static const customer_gender_type_ customer_gender;

    // customer_contact
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_contact_type_;

    static const customer_contact_type_ customer_contact;

    // customer_address
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_address_type_;

    static const customer_address_type_ customer_address;

    // customer_house_number
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_house_number_type_;

    static const customer_house_number_type_ customer_house_number;

    // customer_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    customer_reg_date_type_;

    static const customer_reg_date_type_ customer_reg_date;
  };

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_id_type_
  query_columns< ::customer, id_mysql, A >::
  customer_id (A::table_name, "`customer_id`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_unique_type_
  query_columns< ::customer, id_mysql, A >::
  customer_unique (A::table_name, "`customer_unique`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_branch_type_
  query_columns< ::customer, id_mysql, A >::
  customer_branch (A::table_name, "`customer_branch`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_name_type_
  query_columns< ::customer, id_mysql, A >::
  customer_name (A::table_name, "`customer_name`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_gender_type_
  query_columns< ::customer, id_mysql, A >::
  customer_gender (A::table_name, "`customer_gender`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_contact_type_
  query_columns< ::customer, id_mysql, A >::
  customer_contact (A::table_name, "`customer_contact`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_address_type_
  query_columns< ::customer, id_mysql, A >::
  customer_address (A::table_name, "`customer_address`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_house_number_type_
  query_columns< ::customer, id_mysql, A >::
  customer_house_number (A::table_name, "`customer_house_number`", 0);

  template <typename A>
  const typename query_columns< ::customer, id_mysql, A >::customer_reg_date_type_
  query_columns< ::customer, id_mysql, A >::
  customer_reg_date (A::table_name, "`customer_reg_date`", 0);
}

#include "customer-odb.ixx"

#include <odb/post.hxx>

#endif // CUSTOMER_ODB_HXX
