/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `employee`;

CREATE TABLE `employee` (
  `employee_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `employee_branch` BIGINT UNSIGNED NULL,
  `employee_unique` TEXT NOT NULL,
  `employee_name` TEXT NOT NULL,
  `employee_gender` TEXT NOT NULL,
  `employee_contact` TEXT NOT NULL,
  `employee_address` TEXT NOT NULL,
  `employee_password` TEXT NOT NULL,
  `employee_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `employee`
  ADD CONSTRAINT `employee_employee_branch_fk`
    FOREIGN KEY (`employee_branch`)
    REFERENCES `branch` (`branch_id`)
*/

