// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "employee-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/simple-object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/simple-object-result.hxx>
#include <odb/mysql/enum.hxx>

namespace odb
{
  // employee
  //

  const char alias_traits<  ::branch,
    id_mysql,
    access::object_traits_impl< ::employee, id_mysql >::employee_branch_tag>::
  table_name[] = "`employee_branch`";

  struct access::object_traits_impl< ::employee, id_mysql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      mysql::connection&,
      image_type&,
      id_image_type&,
      mysql::binding&,
      mysql::binding&)
    {
    }
  };

  access::object_traits_impl< ::employee, id_mysql >::id_type
  access::object_traits_impl< ::employee, id_mysql >::
  id (const id_image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.id_value,
        i.id_null);
    }

    return id;
  }

  access::object_traits_impl< ::employee, id_mysql >::id_type
  access::object_traits_impl< ::employee, id_mysql >::
  id (const image_type& i)
  {
    mysql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        id,
        i.employee_id_value,
        i.employee_id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::employee, id_mysql >::
  grow (image_type& i,
        my_bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // employee_id
    //
    t[0UL] = 0;

    // employee_branch
    //
    t[1UL] = 0;

    // employee_unique
    //
    if (t[2UL])
    {
      i.employee_unique_value.capacity (i.employee_unique_size);
      grew = true;
    }

    // employee_name
    //
    if (t[3UL])
    {
      i.employee_name_value.capacity (i.employee_name_size);
      grew = true;
    }

    // employee_gender
    //
    if (t[4UL])
    {
      i.employee_gender_value.capacity (i.employee_gender_size);
      grew = true;
    }

    // employee_contact
    //
    if (t[5UL])
    {
      i.employee_contact_value.capacity (i.employee_contact_size);
      grew = true;
    }

    // employee_address
    //
    if (t[6UL])
    {
      i.employee_address_value.capacity (i.employee_address_size);
      grew = true;
    }

    // employee_password
    //
    if (t[7UL])
    {
      i.employee_password_value.capacity (i.employee_password_size);
      grew = true;
    }

    // employee_reg_date
    //
    if (t[8UL])
    {
      i.employee_reg_date_value.capacity (i.employee_reg_date_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  bind (MYSQL_BIND* b,
        image_type& i,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    std::size_t n (0);

    // employee_id
    //
    if (sk != statement_update)
    {
      b[n].buffer_type = MYSQL_TYPE_LONGLONG;
      b[n].is_unsigned = 1;
      b[n].buffer = &i.employee_id_value;
      b[n].is_null = &i.employee_id_null;
      n++;
    }

    // employee_branch
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.employee_branch_value;
    b[n].is_null = &i.employee_branch_null;
    n++;

    // employee_unique
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_unique_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_unique_value.capacity ());
    b[n].length = &i.employee_unique_size;
    b[n].is_null = &i.employee_unique_null;
    n++;

    // employee_name
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_name_value.capacity ());
    b[n].length = &i.employee_name_size;
    b[n].is_null = &i.employee_name_null;
    n++;

    // employee_gender
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_gender_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_gender_value.capacity ());
    b[n].length = &i.employee_gender_size;
    b[n].is_null = &i.employee_gender_null;
    n++;

    // employee_contact
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_contact_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_contact_value.capacity ());
    b[n].length = &i.employee_contact_size;
    b[n].is_null = &i.employee_contact_null;
    n++;

    // employee_address
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_address_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_address_value.capacity ());
    b[n].length = &i.employee_address_size;
    b[n].is_null = &i.employee_address_null;
    n++;

    // employee_password
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_password_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_password_value.capacity ());
    b[n].length = &i.employee_password_size;
    b[n].is_null = &i.employee_password_null;
    n++;

    // employee_reg_date
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.employee_reg_date_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.employee_reg_date_value.capacity ());
    b[n].length = &i.employee_reg_date_size;
    b[n].is_null = &i.employee_reg_date_null;
    n++;
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::employee, id_mysql >::
  init (image_type& i,
        const object_type& o,
        mysql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace mysql;

    bool grew (false);

    // employee_id
    //
    if (sk == statement_insert)
    {
      long unsigned int const& v =
        o.employee_id;

      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.employee_id_value, is_null, v);
      i.employee_id_null = is_null;
    }

    // employee_branch
    //
    {
      ::boost::shared_ptr< ::branch > const& v =
        o.employee_branch;

      typedef object_traits< ::branch > obj_traits;
      typedef odb::pointer_traits< ::boost::shared_ptr< ::branch > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_image (
          i.employee_branch_value, is_null, id);
        i.employee_branch_null = is_null;
      }
      else
        i.employee_branch_null = 1;
    }

    // employee_unique
    //
    {
      ::std::string const& v =
        o.employee_unique;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_unique_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_unique_value,
        size,
        is_null,
        v);
      i.employee_unique_null = is_null;
      i.employee_unique_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_unique_value.capacity ());
    }

    // employee_name
    //
    {
      ::std::string const& v =
        o.employee_name;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_name_value,
        size,
        is_null,
        v);
      i.employee_name_null = is_null;
      i.employee_name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_name_value.capacity ());
    }

    // employee_gender
    //
    {
      ::std::string const& v =
        o.employee_gender;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_gender_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_gender_value,
        size,
        is_null,
        v);
      i.employee_gender_null = is_null;
      i.employee_gender_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_gender_value.capacity ());
    }

    // employee_contact
    //
    {
      ::std::string const& v =
        o.employee_contact;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_contact_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_contact_value,
        size,
        is_null,
        v);
      i.employee_contact_null = is_null;
      i.employee_contact_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_contact_value.capacity ());
    }

    // employee_address
    //
    {
      ::std::string const& v =
        o.employee_address;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_address_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_address_value,
        size,
        is_null,
        v);
      i.employee_address_null = is_null;
      i.employee_address_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_address_value.capacity ());
    }

    // employee_password
    //
    {
      ::std::string const& v =
        o.employee_password;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_password_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_password_value,
        size,
        is_null,
        v);
      i.employee_password_null = is_null;
      i.employee_password_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_password_value.capacity ());
    }

    // employee_reg_date
    //
    {
      ::std::string const& v =
        o.employee_reg_date;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.employee_reg_date_value.capacity ());
      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_image (
        i.employee_reg_date_value,
        size,
        is_null,
        v);
      i.employee_reg_date_null = is_null;
      i.employee_reg_date_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.employee_reg_date_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // employee_id
    //
    {
      long unsigned int& v =
        o.employee_id;

      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_value (
        v,
        i.employee_id_value,
        i.employee_id_null);
    }

    // employee_branch
    //
    {
      ::boost::shared_ptr< ::branch >& v =
        o.employee_branch;

      typedef object_traits< ::branch > obj_traits;
      typedef odb::pointer_traits< ::boost::shared_ptr< ::branch > > ptr_traits;

      if (i.employee_branch_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        mysql::value_traits<
            obj_traits::id_type,
            mysql::id_ulonglong >::set_value (
          id,
          i.employee_branch_value,
          i.employee_branch_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<mysql::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }

    // employee_unique
    //
    {
      ::std::string& v =
        o.employee_unique;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_unique_value,
        i.employee_unique_size,
        i.employee_unique_null);
    }

    // employee_name
    //
    {
      ::std::string& v =
        o.employee_name;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_name_value,
        i.employee_name_size,
        i.employee_name_null);
    }

    // employee_gender
    //
    {
      ::std::string& v =
        o.employee_gender;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_gender_value,
        i.employee_gender_size,
        i.employee_gender_null);
    }

    // employee_contact
    //
    {
      ::std::string& v =
        o.employee_contact;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_contact_value,
        i.employee_contact_size,
        i.employee_contact_null);
    }

    // employee_address
    //
    {
      ::std::string& v =
        o.employee_address;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_address_value,
        i.employee_address_size,
        i.employee_address_null);
    }

    // employee_password
    //
    {
      ::std::string& v =
        o.employee_password;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_password_value,
        i.employee_password_size,
        i.employee_password_null);
    }

    // employee_reg_date
    //
    {
      ::std::string& v =
        o.employee_reg_date;

      mysql::value_traits<
          ::std::string,
          mysql::id_string >::set_value (
        v,
        i.employee_reg_date_value,
        i.employee_reg_date_size,
        i.employee_reg_date_null);
    }
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      mysql::value_traits<
          long unsigned int,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::employee, id_mysql >::persist_statement[] =
  "INSERT INTO `employee` "
  "(`employee_id`, "
  "`employee_branch`, "
  "`employee_unique`, "
  "`employee_name`, "
  "`employee_gender`, "
  "`employee_contact`, "
  "`employee_address`, "
  "`employee_password`, "
  "`employee_reg_date`) "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::employee, id_mysql >::find_statement[] =
  "SELECT "
  "`employee`.`employee_id`, "
  "`employee`.`employee_branch`, "
  "`employee`.`employee_unique`, "
  "`employee`.`employee_name`, "
  "`employee`.`employee_gender`, "
  "`employee`.`employee_contact`, "
  "`employee`.`employee_address`, "
  "`employee`.`employee_password`, "
  "`employee`.`employee_reg_date` "
  "FROM `employee` "
  "WHERE `employee`.`employee_id`=?";

  const char access::object_traits_impl< ::employee, id_mysql >::update_statement[] =
  "UPDATE `employee` "
  "SET "
  "`employee_branch`=?, "
  "`employee_unique`=?, "
  "`employee_name`=?, "
  "`employee_gender`=?, "
  "`employee_contact`=?, "
  "`employee_address`=?, "
  "`employee_password`=?, "
  "`employee_reg_date`=? "
  "WHERE `employee_id`=?";

  const char access::object_traits_impl< ::employee, id_mysql >::erase_statement[] =
  "DELETE FROM `employee` "
  "WHERE `employee_id`=?";

  const char access::object_traits_impl< ::employee, id_mysql >::query_statement[] =
  "SELECT\n"
  "`employee`.`employee_id`,\n"
  "`employee`.`employee_branch`,\n"
  "`employee`.`employee_unique`,\n"
  "`employee`.`employee_name`,\n"
  "`employee`.`employee_gender`,\n"
  "`employee`.`employee_contact`,\n"
  "`employee`.`employee_address`,\n"
  "`employee`.`employee_password`,\n"
  "`employee`.`employee_reg_date`\n"
  "FROM `employee`\n"
  "LEFT JOIN `branch` AS `employee_branch` ON `employee_branch`.`branch_id`=`employee`.`employee_branch`";

  const char access::object_traits_impl< ::employee, id_mysql >::erase_query_statement[] =
  "DELETE FROM `employee`";

  const char access::object_traits_impl< ::employee, id_mysql >::table_name[] =
  "`employee`";

  void access::object_traits_impl< ::employee, id_mysql >::
  persist (database& db, object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    im.employee_id_value = 0;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    {
      id_image_type& i (sts.id_image ());
      binding& b (sts.id_image_binding ());
      if (i.version != sts.id_image_version () || b.version == 0)
      {
        bind (b.bind, i);
        sts.id_image_version (i.version);
        b.version++;
      }
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.employee_id = id (sts.id_image ());

    callback (db,
              static_cast<const object_type&> (obj),
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace mysql;
    using mysql::update_statement;

    callback (db, obj, callback_event::pre_update);

    mysql::transaction& tr (mysql::transaction::current ());
    mysql::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj.employee_id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::employee, id_mysql >::
  erase (database& db, const id_type& id)
  {
    using namespace mysql;

    ODB_POTENTIALLY_UNUSED (db);

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::employee, id_mysql >::pointer_type
  access::object_traits_impl< ::employee, id_mysql >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::employee, id_mysql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::employee, id_mysql >::
  reload (database& db, object_type& obj)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj.employee_id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::employee, id_mysql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::employee, id_mysql >::object_type >
  access::object_traits_impl< ::employee, id_mysql >::
  query (database&, const query_base_type& q)
  {
    using namespace mysql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) mysql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::employee, id_mysql >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace mysql;

    mysql::connection& conn (
      mysql::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
