/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `meter`;

CREATE TABLE `meter` (
  `meter_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `meter_unique` TEXT NOT NULL,
  `meter_customer` BIGINT UNSIGNED NULL,
  `meter_owner` TEXT NOT NULL,
  `meter_number` TEXT NOT NULL,
  `meter_intital_unit` TEXT NOT NULL,
  `meter_joinging_price` TEXT NOT NULL,
  `meter_lock` ENUM('Yes', 'No') NULL DEFAULT 'No',
  `meter_in_service` TEXT NOT NULL,
  `meter_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `meter`
  ADD CONSTRAINT `meter_meter_customer_fk`
    FOREIGN KEY (`meter_customer`)
    REFERENCES `customer` (`customer_id`)
*/

