/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `payments`;

CREATE TABLE `payments` (
  `pay_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `pay_unique` TEXT NOT NULL,
  `pay_bill` BIGINT UNSIGNED NULL,
  `pay_customer` BIGINT UNSIGNED NULL,
  `pay_method` TEXT NOT NULL,
  `pay_type` TEXT NOT NULL,
  `pay_amount` TEXT NOT NULL,
  `pay_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `payments`
  ADD CONSTRAINT `payments_pay_bill_fk`
    FOREIGN KEY (`pay_bill`)
    REFERENCES `bill` (`bill_id`),
  ADD CONSTRAINT `payments_pay_customer_fk`
    FOREIGN KEY (`pay_customer`)
    REFERENCES `customer` (`customer_id`)
*/

