/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Price`;

CREATE TABLE `Price` (
  `price_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `price_unique` TEXT NOT NULL,
  `price_item` TEXT NOT NULL,
  `price_amount` TEXT NOT NULL,
  `price_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

