/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Task`;

CREATE TABLE `Task` (
  `task_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `task_unique` TEXT NOT NULL,
  `task_employee` BIGINT UNSIGNED NULL,
  `task_item` TEXT NOT NULL,
  `task_amount` TEXT NOT NULL,
  `task_start` TEXT NOT NULL,
  `task_end` TEXT NOT NULL,
  `task_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `Task`
  ADD CONSTRAINT `Task_task_employee_fk`
    FOREIGN KEY (`task_employee`)
    REFERENCES `employee` (`employee_id`)
*/

