// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TASKS_ODB_HXX
#define TASKS_ODB_HXX

// Begin prologue.
//
#include <odb/boost/smart-ptr/pointer-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "tasks.hxx"

#include "branch-odb.hxx"
#include "employee-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#ifdef BOOST_TR1_MEMORY_HPP_INCLUDED
#  include <odb/tr1/wrapper-traits.hxx>
#  include <odb/tr1/pointer-traits.hxx>
#endif
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // Task
  //
  template <>
  struct class_traits< ::Task >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::Task >
  {
    public:
    typedef ::Task object_type;
    typedef ::boost::shared_ptr< ::Task > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // Task
  //
  template <typename A>
  struct pointer_query_columns< ::Task, id_mysql, A >
  {
    // task_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    task_id_type_;

    static const task_id_type_ task_id;

    // task_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_unique_type_;

    static const task_unique_type_ task_unique;

    // task_employee
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    task_employee_type_;

    static const task_employee_type_ task_employee;

    // task_item
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_item_type_;

    static const task_item_type_ task_item;

    // task_amount
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_amount_type_;

    static const task_amount_type_ task_amount;

    // task_start
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_start_type_;

    static const task_start_type_ task_start;

    // task_end
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_end_type_;

    static const task_end_type_ task_end;

    // task_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_reg_date_type_;

    static const task_reg_date_type_ task_reg_date;
  };

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_id_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_id (A::table_name, "`task_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_unique_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_unique (A::table_name, "`task_unique`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_employee_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_employee (A::table_name, "`task_employee`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_item_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_item (A::table_name, "`task_item`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_amount_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_amount (A::table_name, "`task_amount`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_start_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_start (A::table_name, "`task_start`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_end_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_end (A::table_name, "`task_end`", 0);

  template <typename A>
  const typename pointer_query_columns< ::Task, id_mysql, A >::task_reg_date_type_
  pointer_query_columns< ::Task, id_mysql, A >::
  task_reg_date (A::table_name, "`task_reg_date`", 0);

  template <>
  class access::object_traits_impl< ::Task, id_mysql >:
    public access::object_traits< ::Task >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // task_id
      //
      unsigned long long task_id_value;
      my_bool task_id_null;

      // task_unique
      //
      details::buffer task_unique_value;
      unsigned long task_unique_size;
      my_bool task_unique_null;

      // task_employee
      //
      unsigned long long task_employee_value;
      my_bool task_employee_null;

      // task_item
      //
      details::buffer task_item_value;
      unsigned long task_item_size;
      my_bool task_item_null;

      // task_amount
      //
      details::buffer task_amount_value;
      unsigned long task_amount_size;
      my_bool task_amount_null;

      // task_start
      //
      details::buffer task_start_value;
      unsigned long task_start_size;
      my_bool task_start_null;

      // task_end
      //
      details::buffer task_end_value;
      unsigned long task_end_size;
      my_bool task_end_null;

      // task_reg_date
      //
      details::buffer task_reg_date_value;
      unsigned long task_reg_date_size;
      my_bool task_reg_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct task_employee_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::Task, id_common >:
    public access::object_traits_impl< ::Task, id_mysql >
  {
  };

  // Task
  //
  template <>
  struct alias_traits<
    ::employee,
    id_mysql,
    access::object_traits_impl< ::Task, id_mysql >::task_employee_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::Task, id_mysql >
  {
    // task_employee
    //
    typedef
    odb::alias_traits<
      ::employee,
      id_mysql,
      access::object_traits_impl< ::Task, id_mysql >::task_employee_tag>
    task_employee_alias_;
  };

  template <typename A>
  struct query_columns< ::Task, id_mysql, A >:
    query_columns_base< ::Task, id_mysql >
  {
    // task_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    task_id_type_;

    static const task_id_type_ task_id;

    // task_unique
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_unique_type_;

    static const task_unique_type_ task_unique;

    // task_employee
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    task_employee_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::employee,
        id_mysql,
        task_employee_alias_ > >
    task_employee_pointer_type_;

    struct task_employee_type_: task_employee_pointer_type_, task_employee_column_type_
    {
      task_employee_type_ (const char* t, const char* c, const char* conv)
        : task_employee_column_type_ (t, c, conv)
      {
      }
    };

    static const task_employee_type_ task_employee;

    // task_item
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_item_type_;

    static const task_item_type_ task_item;

    // task_amount
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_amount_type_;

    static const task_amount_type_ task_amount;

    // task_start
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_start_type_;

    static const task_start_type_ task_start;

    // task_end
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_end_type_;

    static const task_end_type_ task_end;

    // task_reg_date
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    task_reg_date_type_;

    static const task_reg_date_type_ task_reg_date;
  };

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_id_type_
  query_columns< ::Task, id_mysql, A >::
  task_id (A::table_name, "`task_id`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_unique_type_
  query_columns< ::Task, id_mysql, A >::
  task_unique (A::table_name, "`task_unique`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_employee_type_
  query_columns< ::Task, id_mysql, A >::
  task_employee (A::table_name, "`task_employee`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_item_type_
  query_columns< ::Task, id_mysql, A >::
  task_item (A::table_name, "`task_item`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_amount_type_
  query_columns< ::Task, id_mysql, A >::
  task_amount (A::table_name, "`task_amount`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_start_type_
  query_columns< ::Task, id_mysql, A >::
  task_start (A::table_name, "`task_start`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_end_type_
  query_columns< ::Task, id_mysql, A >::
  task_end (A::table_name, "`task_end`", 0);

  template <typename A>
  const typename query_columns< ::Task, id_mysql, A >::task_reg_date_type_
  query_columns< ::Task, id_mysql, A >::
  task_reg_date (A::table_name, "`task_reg_date`", 0);
}

#include "tasks-odb.ixx"

#include <odb/post.hxx>

#endif // TASKS_ODB_HXX
