/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `unit`;

CREATE TABLE `unit` (
  `unit_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `unit_unique` TEXT NOT NULL,
  `unit_branch` BIGINT UNSIGNED NULL,
  `unit_price` TEXT NOT NULL,
  `unit_reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

/*
ALTER TABLE `unit`
  ADD CONSTRAINT `unit_unit_branch_fk`
    FOREIGN KEY (`unit_branch`)
    REFERENCES `branch` (`branch_id`)
*/

