/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `company` TEXT NOT NULL,
  `phone` TEXT NOT NULL,
  `password` TEXT NOT NULL,
  `reg_date` TEXT NOT NULL)
 ENGINE=InnoDB;

